--- a/security/integrity/Makefile
+++ b/security/integrity/Makefile
@@ -20,5 +20,6 @@
                                      platform_certs/keyring_handler.o
 integrity-$(CONFIG_EFI) += efi_secureboot.o
 # The relative order of the 'ima' and 'evm' LSMs depends on the order below.
+obj-$(CONFIG_IMA_RTMR)			+= ima_rtmr/
 obj-$(CONFIG_IMA)			+= ima/
 obj-$(CONFIG_EVM)			+= evm/
